"""phase2_initial_schema

Revision ID: dc544dbaab6c
Revises: 
Create Date: 2026-10-06 04:00:30.951221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc544dbaab6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_windows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscriberId', sa.String(length=255), nullable=False),
    sa.Column('workflowId', sa.String(length=255), nullable=False),
    sa.Column('digestKey', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'EXPIRED', 'DISPATCHED', name='digestwindow_status'), nullable=False),
    sa.Column('masterJobId', sa.String(length=36), nullable=False),
    sa.Column('windowEndsAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eventCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_digest_window_open_unique', 'digest_windows', ['subscriberId', 'workflowId', 'digestKey'], unique=True, postgresql_where="status = 'OPEN'")
    op.create_index(op.f('ix_digest_windows_subscriberId'), 'digest_windows', ['subscriberId'], unique=False)
    op.create_index(op.f('ix_digest_windows_windowEndsAt'), 'digest_windows', ['windowEndsAt'], unique=False)
    op.create_index(op.f('ix_digest_windows_workflowId'), 'digest_windows', ['workflowId'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscriberId', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    op.create_index(op.f('ix_subscribers_subscriberId'), 'subscribers', ['subscriberId'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isCritical', sa.Boolean(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transactionId', sa.String(length=128), nullable=False),
    sa.Column('subscriberId', sa.String(length=255), nullable=False),
    sa.Column('workflowId', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'MERGED', 'COMPLETED', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('digestWindowId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['digestWindowId'], ['digest_windows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriberId'], ['subscribers.subscriberId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflowId'], ['workflows.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_digestWindowId'), 'notifications', ['digestWindowId'], unique=False)
    op.create_index(op.f('ix_notifications_subscriberId'), 'notifications', ['subscriberId'], unique=False)
    op.create_index(op.f('ix_notifications_transactionId'), 'notifications', ['transactionId'], unique=True)
    op.create_index(op.f('ix_notifications_workflowId'), 'notifications', ['workflowId'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscriberId', sa.String(length=255), nullable=False),
    sa.Column('workflowId', sa.String(length=255), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscriberId'], ['subscribers.subscriberId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflowId'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriberId', 'workflowId', name='uq_preference_subscriber_workflow')
    )
    op.create_index(op.f('ix_preferences_subscriberId'), 'preferences', ['subscriberId'], unique=False)
    op.create_index('ix_preferences_subscriber_workflow', 'preferences', ['subscriberId', 'workflowId'], unique=False)
    op.create_index(op.f('ix_preferences_workflowId'), 'preferences', ['workflowId'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notificationId', sa.String(length=36), nullable=False),
    sa.Column('parentJobId', sa.String(length=36), nullable=True),
    sa.Column('subscriberId', sa.String(length=255), nullable=False),
    sa.Column('stepType', sa.Enum('DIGEST', 'EMAIL', 'IN_APP', name='job_step_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELAYED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'MERGED', name='job_status'), nullable=False),
    sa.Column('skipReason', sa.Enum('SUBSCRIBER_PREFERENCE', 'CONDITIONS_UNMET', name='job_skip_reason'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('maxAttempts', sa.Integer(), nullable=False),
    sa.Column('delayUntil', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('digestMetadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notificationId'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parentJobId'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_delayUntil'), 'jobs', ['delayUntil'], unique=False)
    op.create_index(op.f('ix_jobs_notificationId'), 'jobs', ['notificationId'], unique=False)
    op.create_index(op.f('ix_jobs_parentJobId'), 'jobs', ['parentJobId'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_subscriberId'), 'jobs', ['subscriberId'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jobId', sa.String(length=36), nullable=False),
    sa.Column('subscriberId', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'IN_APP', name='message_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='message_status'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('aiSummary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deduplicationKey', sa.String(length=512), nullable=False),
    sa.Column('providerMessageId', sa.String(length=512), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deliveredAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jobId'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplicationKey')
    )
    op.create_index(op.f('ix_messages_createdAt'), 'messages', ['createdAt'], unique=False)
    op.create_index(op.f('ix_messages_jobId'), 'messages', ['jobId'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_subscriberId'), 'messages', ['subscriberId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_subscriberId'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_jobId'), table_name='messages')
    op.drop_index(op.f('ix_messages_createdAt'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_jobs_subscriberId'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_parentJobId'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_notificationId'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_delayUntil'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_preferences_workflowId'), table_name='preferences')
    op.drop_index('ix_preferences_subscriber_workflow', table_name='preferences')
    op.drop_index(op.f('ix_preferences_subscriberId'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_notifications_workflowId'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_transactionId'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_subscriberId'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_digestWindowId'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_subscribers_subscriberId'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_digest_windows_workflowId'), table_name='digest_windows')
    op.drop_index(op.f('ix_digest_windows_windowEndsAt'), table_name='digest_windows')
    op.drop_index(op.f('ix_digest_windows_subscriberId'), table_name='digest_windows')
    op.drop_index('ix_digest_window_open_unique', table_name='digest_windows', postgresql_where="status = 'OPEN'")
    op.drop_table('digest_windows')
    # ### end Alembic commands ###
